<?php
/**
 * Landofcoder
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Landofcoder.com license that is
 * available through the world-wide-web at this URL:
 * http://landofcoder.com/license
 * 
 * DISCLAIMER
 * 
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 * 
 * @category   Landofcoder
 * @package    Lof_SubDomain
 * @copyright  Copyright (c) 2017 Landofcoder (https://landofcoder.com/)
 * @license    https://landofcoder.com/LICENSE-1.0.html
 */

namespace Lofmp\SubDomain\Setup;

use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;

class InstallSchema implements InstallSchemaInterface
{
	public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
	{
		$installer = $setup; 
        $installer->startSetup();
        /**
         * Create table 'lofmp_subdomain'
         */
        $table = $installer->getConnection()->newTable(
            $installer->getTable('lofmp_subdomain_url')
        )->addColumn(
            'id',
            \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
            null,
            ['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
            'ID'
        )->addColumn(
            'name',
             \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
             255,
             [],
             'Name'
        )->addColumn(
            'url_rewrite_ids',
             \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
             '2K',
             [],
             'Url Rewrite Ids'
        )->addColumn(
            'store_id',
            \Magento\Framework\DB\Ddl\Table::TYPE_SMALLINT,
            null,
            ['unsigned' => true, 'nullable' => false, 'default' => '0'],
            'Store Id'
        )->addColumn(
           'entity_id',
            \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
            null,
            ['unsigned' => true, 'nullable' => false],
            'Entity ID'
        )->addColumn(
           'seller_id',
            \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
            null,
            ['unsigned' => true, 'nullable' => false],
            'Seller ID'
        )->addColumn(
           'url_key',
            \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
            null,
            ['unsigned' => true, 'nullable' => false],
            'Url Key'
        )->addColumn(
            'entity_type',
            \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
            32,
            ['unsigned' => true, 'nullable' => false],
            'Entity Type'
        )->addColumn(
            'request_path',
             \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
             255,
             [],
             'Requested Path'
        )->addColumn(
            'target_path',
             \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
             255,
             [],
             'Target Path'
        )->addColumn(
            'is_autogenerated',
            \Magento\Framework\DB\Ddl\Table::TYPE_SMALLINT,
            null,
            ['unsigned' => true, 'default' => '0'],
            'Is Autogenerated'
        )->addColumn(
            'description',
             \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
             255,
             [],
             'Description'
        )->setComment('Lof Seller SubDomain Url');

        $installer->getConnection()->createTable($table);
      
        $installer->endSetup(); 
	}
}